version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "purge-dynamodb-records-dev"
s3_bucket = "common-dev-sam-artifactstore"
s3_prefix = "purge-dynamodb-records-dev"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = """\
    EnvironmentName=\"dev\" \
"""
tags = "project=\"purge-dynamodb-records\" env=\"dev\" IaC=\"cfn\""
confirm_changeset = false

# [stg]
# [stg.deploy]
# [stg.deploy.parameters]
# stack_name = "purge-dynamodb-records-dev"
# s3_bucket = "common-dev-sam-artifactstore"
# s3_prefix = "purge-dynamodb-records-dev"
# region = "ap-northeast-1"
# capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
# parameter_overrides = """\
#     EnvironmentName=\"stg\" \
# """
# tags = "project=\"purge-dynamodb-records\" env=\"stg\" IaC=\"cfn\""
# confirm_changeset = false

# [prd]
# [prd.deploy]
# [prd.deploy.parameters]
# stack_name = "purge-dynamodb-records-dev"
# s3_bucket = "common-dev-sam-artifactstore"
# s3_prefix = "purge-dynamodb-records-dev"
# region = "ap-northeast-1"
# capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
# parameter_overrides = """\
#     EnvironmentName=\"prd\" \
# """
# tags = "project=\"purge-dynamodb-records\" env=\"prd\" IaC=\"cfn\""
# confirm_changeset = false
